const semenikaData = [
    { number: '01', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '02', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '03', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '04', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '05', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '06', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '07', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '08', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '09', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '10', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '11', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '12', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '13', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '14', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '15', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '16', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '17', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '18', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '19', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '20', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '21', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '22', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '23', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '24', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '25', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '26', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '27', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '28', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '29', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '30', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '31', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '32', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '33', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '34', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '35', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '36', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '37', kind: 'Смески, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '38', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '39', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '40', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '41', kind: 'Смески, пшеница Triticum aestivum и Triticum dicoccoides', status: 'Неизползван', activity: 'прегледай'},
    { number: '42', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '43', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '44', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
    { number: '45', kind: 'Базови, пшеница', status: 'Неизползван', activity: 'прегледай'},
]
  export default semenikaData
